version: '3.3'

services:

    monitorr:
        image: monitorr/monitorr
        container_name: monitorr
        volumes:
            - ./monitorr:/app
        environment:
            - TZ=Europe/Madrid
            - PGID=1000
            - PUID=1000
        ports:
            - "8200:80"
        restart: unless-stopped

        